### ISSUE TITLE
Error when logging in. Cannot fetch model list. 

### ISSUE THREAD

**Issue by RedRhumRedRhum** [0xboobface/ctbrec#103]
Even when credentials are inputted, the following errors occur. 

https://i.imgur.com/PuiiBfI.png
and 
https://i.imgur.com/8ywQpD5.png

I even tried with a newly created account and followed a few rooms as a test in a browser. 
The same issues show in CTB (ctbrec-1.13.0-win64-jre)  with the new login info. 

This only happens with CB. The other sites do not have this problem 

Thank you

**Comment by RedRhumRedRhum** [comment]
I had check online state set to every 15 seconds

I'm guessing that is what set the CB time out. 
I should have realized this with past programs I have used. Any refresh rate set to under 4mins will set off a 'too many login attempts' flag. 

I'll report back if setting this to greater than 4mins will resolve it.
Thank you

**Comment by Mush-r00m** [comment]
I had this same issue with another program that used login details to download online models from my accounts followed list, it eventually caused chaturbate to completely disable/delete my account. prolly thought i was a bot/spam/fraud etc. i wasnt even able to re-activate my account or change password.

Not saying ctbrec wiill cause this ofcourse, but its possible chaturbate could take this action, which is why i nolonger use the login method :)

**Comment by RedRhumRedRhum** [comment]
> Not saying ctbrec wiill cause this ofcourse, but its possible chaturbate could take this action, which is why i nolonger use the login method :)

I guess a login is not really necessary. But it is nice to be able to see room thumbs of the 'follow' list you make within CTB.

**Comment by Mush-r00m** [comment]
"If you shut down Capturebate-Node after having it running for several days/weeks/months and try to restart it, you will notice that it will not see your follows list and just restart the attempt again. If you leave it shut off for 24 hours it will work again."

Chaturbate-node was the program i used that caused the issue before i started using ctbrec. And your above statement is correct i noticed it alot since i wasnt able to leave the program running 24/7.
Tho thinkin about it now, chaturbate may of seen the login atempts coming from different IP's so ofton as suspicious since im always behind a vpn.

**Comment by 0xboobface** [comment]
> I had check online state set to every 15 seconds
I'm guessing that is what set the CB time out.

I don't think, that is the problem. I have set to it 10 seconds since I started developing ctbrec and never had a problem. The 10 seconds also is the wait time between a whole iteration. So even if you have 100 models or more, it would do the online check one by one and then start over again. If you have many models, this check can take longer then the interval you set. In that case, ctbrec starts over immediately when an iteration is finished.

I only had a 429, when I added the resolution tag feature without throttling the requests. The request throttle is a very basic/stupid implementation at the moment. Maybe I have to improve that.
It is hard to say what caused the problem.

**Comment by bj73** [comment]
> @RedRhumRedRhum
> Capturebate-Node is having issues with handling room names for some reason now. It will just error out for that room on the next refresh and not capture the stream.

Yes, I'm getting that now - last valid recording I have is Nov. 16, at that time I switched to CTBRec but CB-Node was working then.

I suspect it's just an issue with the formatting of the rtmpdump command - I might look at it later, (I like to have more than one arrow in the quiver as it were :)

> If you shut down Capturebate-Node after having it running for several days/weeks/months and try to restart it, you will notice that it will not see your follows list and just restart the attempt again.

For the Follows list, changing the URL to "https://chaturbate.com/followed-cams/online/" fixed any problem it had detecting models online/offline.

Regarding **CTBRec**, the only reliable configuration I have working is:
v1.10.0 server running on two Ubuntu x64 VPS's along with using v1.13.0 as the client on my Windows machine.
I haven't updated the servers because they work and I've had problems getting the latest builds to log on either using them as standalone or in server/client on my RasPi.  The same log on credentials work fine when I fire up Capturebate-Node again to check.

I only have 6 or less models Followed across three accounts so pretty sure I'm not making too many concurrent log ons.

Have to recheck what happens on the RasPi.

**Comment by RedRhumRedRhum** [comment]
I feel dumb.
It was the settings file that was corrupted.

It works now after deleting the file when CTB was not running and letting CTB recreate the settings file when started again.
