### ISSUE TITLE
Unable to run if JDK11 is installed

### ISSUE THREAD

**Issue by SearchAndDestroy** [0xboobface/ctbrec#106]
I am getting ```An error occurred while starting the application``` without anything in the event log if I have Java JKD11 installed.

```java -version
java version "11.0.1" 2018-10-16 LTS```
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```

It works ok if it's not installed.

**To Reproduce**
1 Install JKD11 via chocolatey: cinst JDK11
2 Run ctbrec.exe (from the -jre or the non-jre release)
3 Get the above error

**Desktop (please complete the following information):**
 - OS: Windows 10 1803 (Build 17134.345)
 - Ctbrec Version 1.13.0 both JRE and non-JRE
 - Standalone

**Log**
ctbrec.log is empty and I have deleted %appdata%\ctbrec folder. Nothing in the Windows event log
The JRE version works perfectly if the JDK11 is not install and java in still
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

**Comment by 0xboobface** [comment]
I tried to reproduce the problem following your steps, but I don't get the error :disappointed: 
I thought the JRE version would be completely independent of the environment, because the jre folder has the highest precedence for the launcher exe. I double-checked this behavior by replacing the jre directory with JDK 10, so that I could clearly see in the logs, which version is used. It always looks for the jre directory before trying to find any other Java installations. 
Obviously under some circumstances, that is not the case, but I don't know the cause for that.

**Comment by 0xboobface** [comment]
> I removed the JDK and JRE for Java 8 (jdk8 8.0.191 and javaruntime 8.0.191 in Chocolatey) and the non jre version is now starting.

Aha, I forgot to increase the required Java version to Java 10 in the launcher settings. So the launcher was happy with your Java 8 installation, even though ctbrec does not work with that anymore. I will adjust that and do some testing on windows.

**Comment by 0xboobface** [comment]
I couldn't exactly reproduce the behavior you described, but with the launcher set to require Java 10, it wouldn't try to start and crash. With Java 8 and 11 installed, it always used 11. Unless there was a jre directory, which always was favored over the other installations.
