### ISSUE TITLE
Version 1.8.0 does not work.

### ISSUE THREAD

**Issue by Ote11o** [0xboobface/ctbrec#137]
Is it possible to restore version 1.8.0 for Windows 32 bit to work?

**Comment by RedRhumRedRhum** [comment]
@Ote11o 
Does not work in what sense?

**Comment by 0xboobface** [comment]
Maybe, but without knowing what isn't working, I can't do anything :smiley:

**Comment by 0xboobface** [comment]
The chaturbate bug has been fixed in 1.13, the bongacams bug in 1.16. I would have to backport those changes and build a newer version. I don't know, if I want to do that, because there will be bugs like these in the future and I would have to do this work over and over again. There is a reason I dropped support for 32 bit. I would suggest switching to a 64 bit OS. If you can't do that, then you might be able to run a 64 bit virtual machine on your 32 bit host.

**Comment by Ote11o** [comment]
I understand. Thank you for your response.
