### ISSUE TITLE
Problems with segments

### ISSUE THREAD

**Issue by quetzalsly** [0xboobface/ctbrec#16]
The program works great, it records the videos just fine but there are a few issues that I just can't seem to solve.

The segments sometimes don't get merged, even if you right click the records and merge. I am left with some folders being full of ts segments and can't do anything about them.

Any time a model disconnects it creates a new video, it would be great if each merged video would be by day, so only a new day would make a new video, the rest is merged into one.

Lastly, the whole segment system is really bad for the HDD, writing thousands of little files. Why can't we just have an option to do this in memory? I don't know what kind of program you use for merging but maybe its API has a 'from memory' option? The settings could have a memory buffer option and if it exceeds that size, then a segment is made. For users with 32gb of ram the memory buffer could last a long time.

**Comment by quetzalsly** [comment]
Forgot to mention, I think the first problem is because it some folders have a 0 size segment or a corrupted one. The program isn't crashing, I just manually click stop recording, the program should not leave 0 size or corrupted segments.

**Comment by idroccolo** [comment]
I used another program before, based on streamlink, and it did everything in ram adding a little bit of data every X seconds to the video file. And I also have problems when there is some corrupt segment.

**Comment by 0xboobface** [comment]
> The segments sometimes don't get merged, even if you right click the records and merge. I am left with some folders being full of ts segments and can't do anything about them.

Can you help me debugging this? Does this recording have a playlist file and does it reflect the directory contents? I had some cases, where the playlist was empty. You also mentioned, that some recordings have segments with a size of 0. Is that the case for this recording?

> Any time a model disconnects it creates a new video, it would be great if each merged video would be by day, so only a new day would make a new video, the rest is merged into one.

This is something I might consider. Sometimes models have unstable internet connections and you end up with quite a few recordings.

> Your concerns about the segments

Originally I didn't intent to merge the files at all, because that is something, which should be done by a proper video library like ffmpeg (because of timestamp corrections and what not) and I didn't want to introduce such dependency. The playlists are generated so that you still can play a recording in one go. Players like VLC and mpv support these playlists (they are also used to stream the recordings, if you run ctbrec in client/server mode like I do).
I think I'll revise the merging, so that it works as intended and then maybe have a look at how ffmpeg could be used to do that.

**Comment by quetzalsly** [comment]
It makes a playlist file but sometimes it also makes a 0 size file and a .CORRUPT file. If I remove these manually and restart the program, then the merge can be made. Why do you want to remove the merge option? its so convienient to have one single file, why would you want to keep thousands of tiny files around? Honestly it would be great if it could be done in memory, without the tiny files xD. At least maybe have an option to select your preferred method, I am sure some people don't mind the thousands of files. I like to keep my files small and tidy.

**Comment by idroccolo** [comment]
I also think that the whole system of segments is a suicide for our hard drived. Way better keeping a little "cache" of thr last segments on RAM and adding directly the last segments to a single file growing little by little. Many programs do that.

**Comment by 0xboobface** [comment]
I totally agree with you both. The problem is (and that is also currently true for the merging), that saving the segments in one file can result in a video with invalid timestamps. For example, if a segment is missed or if it is corrupt. And that results in weird behaviour in the player, if you try to jump forwards or backwards in the video.
That is why I originally didn't want to merge the files at all. But I'm currently playing around with FFmpeg to download/merge the files, so that a future version might get rid of the segments.

And concerning SSDs: This isn't a problem at all. The data has to be written to the hard disk. If it is one big file or many small ones doesn't make a big difference. It would make a difference, if data would be written over and over again, but that isn't the case. It's only written once. It can be taxing on the file system / CPU to read a directory with many files, though.

**Comment by idroccolo** [comment]
Whwnwver opening a volder full of segments, drives are stressed because Windows tries to generate the thumbnail for every segment. Also, it is very bad for the Master File Table.

**Comment by 0xboobface** [comment]
Version 1.5.0 merges the segments into one file while downloading. I found a MPEG streaming server, which I managed to modify and integrate to do proper merging with timestamp and continuity fixing.
