### ISSUE TITLE
"Bug/ish" Login Failed-Couldnt fetch model list "403 Unauthorized" "429 Too Many Requests"

### ISSUE THREAD

**Issue by Mush-r00m** [0xboobface/ctbrec#2]
This is not entirely a bug with your program specificly, i also suffer this issue when using "Chaturbate-Node"   
Most of the time i will have to let chaturbate node run for hours until its able to login and fetch the model list.  Ive noticed chaturbate using captcha sometimes when logging into their website, so this could be causing the issue.

**Comment by 0xboobface** [comment]
429 Too Many Requests means what it says, there were too many requests fired from your IP. ctbrec shouldn't do that, because the updates are triggered not very frequently. Maybe it was Chaturbate-Node. Try closing both applications (Chaturbate-Node and ctbrec), wait for one hour (because they have a cooldown for 429) and then try again.
