### ISSUE TITLE
how to install it on ubuntu?

### ISSUE THREAD

**Issue by tarelt** [0xboobface/ctbrec#25]
Hi

I'm new on ubuntu and unable to make it work, I'm geting this error:

$ '/home/o/Downloads/ctbrec-1.4.1-linux/ctbrec/ctbrec.sh' 
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)
Error: Could not find or load main class ctbrec.ui.Launcher
Caused by: java.lang.ClassNotFoundException: ctbrec.ui.Launcher

by the way, the windows version worked well, I realy liked it.

thanks.

**Comment by 0xboobface** [comment]
This is an issue I overlooked. The problem is, that OpenJDK does not come with JavaFX, which ctbrec uses as the window toolkit. You can solve the problem by downloading Java 10 from http://www.oracle.com/technetwork/java/javase/downloads/index.html. Download the jre-10.0.2_linux-x64_bin.tar.gz, extract it into the ctbrec directory, rename it to jre for simplicity. Then open ctbrec.sh and replace `JAVA=java` with `JAVA=jre/bin/java`

**Comment by 0xboobface** [comment]
Alternatively you can search the ubuntu repository for OpenJFX and install that. But my first solution is guaranteed to work.

**Comment by tarelt** [comment]
Thanks for the reply

I still get the same error, despite the change from "OpenJDK" to "Java", and I had a problem with JAVA=jre/bin/java ("jre/bin/java: not found"), so I had to put the complete path. I'm trying linux, but look like it is not for me...

anyway, thanks for the reply.

error:
$ '/home/o/Downloads/ctbrec-1.4.3-linux/ctbrec/ctbrec.sh' 
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
Error: Could not find or load main class ctbrec.ui.Launcher
Caused by: java.lang.ClassNotFoundException: ctbrec.ui.Launcher

**Comment by 0xboobface** [comment]
try
`$ cd '/home/o/Downloads/ctbrec-1.4.3-linux/ctbrec/`
`$ ./ctbrec.sh`

**Comment by tarelt** [comment]
Thanks man
It's working fine now, sorry for all burden.
