### ISSUE TITLE
Suggestion: Hide models that are in private/group

### ISSUE THREAD

**Issue by Qwatuz** [0xboobface/ctbrec#28]
When browsing it would be great if models were hidden if they are in group/private/anything other than public chat - Maybe an option or default setting?

**Comment by 0xboobface** [comment]
I would like to have this feature, too. The problem I see is, that this information is not available on the overview pages. You have to request it for each model. And to have it up-to-date, you would have to do that every 1 or 2 minutes. For each overview page, that would be ~80 requests per minute. I' m a bit worried to get blocked / timed out firing so many requests.

**Comment by 0xboobface** [comment]
In the next version you will be able to filter public rooms by entering "public" as one of the keywords in the filter bar. You have to switch on "Display stream resolution in overview" in the settings for this to work.
I'm using a cache, so that the application doesn't do too many requests. Entries in this cache expire after 5 minutes. That means, that changes to the room status will be visible after 5 minutes at worst. It also takes some time for the cache to fill, because the number of requests per second are limited to 2.

It is a compromise of having the functionality and not being blocked. I still think, it works quite well.

BTW: the recorder is unaffected by this and will start a recording almost immediately, when a room becomes public.
