### ISSUE TITLE
Still recording in chunks without merging in 1.5.2

### ISSUE THREAD

**Issue by wofnull** [0xboobface/ctbrec#31]
![1 5 2-notmerging](https://user-images.githubusercontent.com/449003/46499444-62fc2300-c820-11e8-946a-8d3f231d55ed.PNG)

As seen in picture above, when in servermode recording with root privileges, there is no merging happening in any way , even after stream ends or the server is rebooted ... strange enough, the merging worked in versions before 1.5.x without any problems for me.  The setting for Autosplit is set to 3600 ( 60 Minutes ) , disabling it, has no effect at all

Any idea from what this could be caused?

**Comment by 0xboobface** [comment]
That behaviour is intended. In server mode, a recording is not merged automatically, but instead a playlist is generated. That is done, because the server also acts as a streaming server, so that a media player can be used to play the recording directly from the server. Using a playlist enables the media player to jump very fast in the recording, because only the currently played segments have to be downloaded.

If you want to merge a recording, just connect to server with the client app and download the recording. Afterwards you can decide, if you want to delete the recording on the server, or keep it.

**Comment by bronis75** [comment]
There is no way to get an automatic merge ?

**Comment by 0xboobface** [comment]
@bronis75 At the moment there is no way to merge files on the server with ctbrec. You can of course use ffmpeg or other external tools to do that.

This would just remux the files. I'm not sure, if this also fixes timestamps etc.
```ffmpeg -i playlist.m3u8 -c:v copy -c:a copy -f mp4 output.mp4```

To be sure to get a valid mp4 file, recode the file. With this method you can also use another encoder like x265 to get smaller files.
```ffmpeg -i playlist.m3u8 -f mp4 output.mp4```

**Comment by preee12** [comment]
Could you please reconsider this? I'm still using 1.3.0 on my server. I tried 1.6.1 today and noticed merging is gone. Is splitting disabled for client/server usage too? Because the option was greyed out.

**Comment by 0xboobface** [comment]
If you run the server, there is no merging and no splitting. The ts-segments are just downloaded and when the recording is finished, a playlist is generated. That's all.
