### ISSUE TITLE
avi or flv?

### ISSUE THREAD

**Issue by JesusChrist777** [0xboobface/ctbrec#37]
add more format pls

**Comment by 0xboobface** [comment]
Sorry, that is not going to happen. The recorded transport stream file (.ts) contains a h264 and a aac track. The file should be playable by any modern media player. If you need it to be any other container format, you can easily remux it with programs like Avidemux, Virtualdub or even ffmpeg.

**Comment by JesusChrist777** [comment]
why not add mp4 instead of .ts?

**Comment by JesusChrist777** [comment]
and the new update contains what? because there's no files to run the app in the new folder

**Comment by 0xboobface** [comment]
> why not add mp4 instead of .ts?

Because I would have to write my own demuxer for MPEG ts and a muxer for MP4 and that is not an easy task. Alternatively I could execute ffmpeg and let it do it, but I don't want to have a dependecy to an external program, because it makes things complicated.

I was thinking about adding a setting to specify a program to run when a recording is finished. You could use that to remux the recording to mp4.

**Comment by JesusChrist777** [comment]
Hey

Well , using  a encoder like handbrake takes alot of gpu cpu power. And i
dont like that, theres  afree converter that support .ts that i used to
then upload videos on pornhub . My account got deleted cause of the content
from others xd.

Anyway. I'd be you, like if i had the coding knowledge, i'd add a feature
to automaticly upload the folder that contains  the newly recorded files.
Like pornhub but again, would require the final video to be mp4 or flv and
not .ts.


Imagine your program, set to record 5 min videos, in mp4, and set to
automaticly upload the files to the desired porn site of your choice, for
profit or non profit, it would be  a machine gun.
And a feature to automaticly deleted the uploaded files and  a live stats
feature to display the videos uploaded, remaining, percentages etc etc.
File size etc etc

It would literaly upload content and content but again, lets pretend i have
an account and i got 1k videos from chaturbate people there, it could get
deleted easily cause of  the copyright. So maybe an auto account creator
and something to set how many videos to be uploaded there. I dont know

But the mp4 feature would  be cool because .ts must be converted into mp4
to be uploaded somewhere.

Thanks  for your time

Le 6 nov. 2018 20:20, "0xboobface" <notifications@github.com> a écrit :

why not add mp4 instead of .ts?

Because I would have to write my own demuxer for MPEG ts and a muxer for
MP4 and that is not an easy task. Alternatively I could execute ffmpeg and
let it do it, but I don't want to have a dependecy to an external program,
because it makes things complicated.

I was thinking about adding a setting to specify a program to run when a
recording is finished. You could use that to remux the recording to mp4.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/0xboobface/ctbrec/issues/37#issuecomment-436375569>,
or mute
the thread

**Comment by 0xboobface** [comment]
> Well , using a encoder like handbrake takes alot of gpu cpu power.

There is a difference between re-encoding and remuxing. The .ts files already contain H264 video and AAC audio. To get a mp4 file you don't need do encode it again. Instead of that, you have to remux it, which means, that the video and audio tracks are extracted from the ts file and "copied" to a mp4 file. You can do that with ffmpeg or avidemux (set codecs to copy) for example.

Concerning uploading the videos to platforms like pornhub:
The next version will include a Post-Processing setting, where you can specify a script, which does whatever you want to do with the files (including remuxing them to mp4). I'll probably include an example script.

Besides that, I don't endorse sharing the recordings on the internet. They should be for personal use and don't harm the models.

**Comment by JesusChrist777** [comment]
Well, for the sharing / harming models, it got taken down anyway so i wont
waste my time with that any more.

But imagine your script being able to farm, a beast machine - record/upload
-non stop haha
im not that silly tho, your script is able to do what a paid recorder cant
do, whitch is to record many scenes at the same time. its a cool script,
but i wont use it to upload on ph and get it taken down haha , had couple
thousands views tho. and nearly 200 vids.

as for the encoding stuff, i had to upload the files there :
https://convert-video-online.com/ to convert them into mp4 since ph dont
alow .ts files
i used that side because even the remux stuff takes cpu

ur script did what i wanted to, because i was looking for a script that
could record many ctb people at the same time. i needed it, i found ur
script, used it, worked well , now i can die in peace haaha

thanks for your time and keep up the good work!
