### ISSUE TITLE
Using ctbrec on macOS

### ISSUE THREAD

**Issue by ItsN3rdy** [0xboobface/ctbrec#38]
Was wondering if you can help me with the steps to use this on macOS. I tried running the .sh file from the Linux installation in Terminal but I get. 

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Error: Could not find or load main class ctbrec.ui.Launcher

**Comment by 0xboobface** [comment]
Two ideas:
1. Did you run the shell script from within the ctbrec directory?
2. It might be the case, that you Java installation does not come with JavaFX. Are you using the oracle JRE or something else?

**Comment by Asynchr0nous** [comment]
Download Java Runtime Enrionment from https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html and extract it to your desired location

Open terminal and run this command (change the path to where ever you saved the above download)

`export JAVA_HOME=/Users/admin/Documents/Virtual\ Machines.localized/jre1.8.0_191.jre/Contents/Home `

Close/Restart your terminal for changes to take affect

To run the script do:

`cd /path/to/ctbrec`

then:

`./ctbrec.sh`

**Comment by Asynchr0nous** [comment]
I made a separate thread on how to get the script working on mac BUT i believe this issue is something else. why? because i'm able to run release version fine but not if I download master/dev version. 

with the master/dev version I encounter two different issues, first which is `${name.final}.jar: bad substitution` which and be fixed by simply adding backslash before after the `$` so it becomes `$\{name.final}.jar`

second issue relates to this issues which if I had to guess is being produced because it doesn't include the jar file. the jar file is only included in release version. I tried to copy it to the master/dev folder but still gave me the same error.

**Comment by 0xboobface** [comment]
> because i'm able to run release version fine but not if I download master/dev version

The master/dev version are no releases. Those downloads are snapshots of the "development environment" and are not supposed to be used by normal users. ${name.final} is a variable and gets replaced by the actual file name during the build process. If you want the final product, you have to download a release from https://github.com/0xboobface/ctbrec/releases or you have to build ctbrec yourself with maven.

Thanks for clarifying. I didn't think people would try to go this route, but that is definitely a possibility.

**Comment by Asynchr0nous** [comment]
>If you want the final product, you have to download a release from https://github.com/0xboobface/ctbrec/releases or you have to build ctbrec yourself with maven.

Yeah I didn't realise that till after that comment. I generally like to try out the latest version which generally means either wating for a release or building it myself. And you're right 99.9% of people will not go down this route since the whole point of this gui is not to mess around with anything and just get the job done.

**Comment by 0xboobface** [comment]
Building ctbrec in a nutshell:

- Install Java (https://www.oracle.com/technetwork/java/index.html)
- Install Maven (http://maven.apache.org/)
- Install Git
- Clone ctbrec with git
- Open a terminal
- cd into the ctbrec directory
- run mvn clean verify
- cd target
- ls 
- voila!

**Comment by Asynchr0nous** [comment]
sweet! 

will give it a go now
