### ISSUE TITLE
CTB Recorder 1.6.0 freezes (Not Responding) when launched

### ISSUE THREAD

**Issue by Mush-r00m** [0xboobface/ctbrec#39]
Hello, when launching & changing tabs in the current ctbrec-1.6.0-win64.zip  it constantly freezes (Not Responding) for 30secs-1min.  1.5.4 works flawlessly.
https://imgur.com/zMSCna1

im running this on local mode , windows 64bit home premium. 8 gigs ram, 6core cpu, running most current version of java for windows.
Disabling myfreecams in settings doesnt result in any change.

**Comment by 0xboobface** [comment]
Not sure why this happens. I tested on Windows 10 and double checked right know. Unfortunately I cannot reproduce this behaviour. You could try to rename the settings.json, so that you have a fresh start. Maybe that helps.

Close ctbrec
<kbd>WINDOWS</kbd> + <kbd>r</kbd>
%appdata%\ctbrec
<kbd>ENTER</kbd>
Rename settings.json
Start ctbrec again.

**Comment by Mush-r00m** [comment]
Yeah, i had to delete the sessings.json file and manually re-add all the chaturbate models i was tracking

**Comment by Mush-r00m** [comment]
Yes it worked, how would you like me to send you the settings file?

**Comment by 0xboobface** [comment]
Maybe create a gist here on github or post it to pastebin or a similar site.

And just for documentation / future reference (since you already readded all models): If you open the settings file in a text editor, you can see all the models in there. Instead of re-adding them manually, you could have copied that structure over to the new settings file. Maybe that would have caused the problem again... But then we would have known, that the problem lies in that structure.

Woulda, shoulda, coulda :) Anyways, thanks for helping to debug this.

**Comment by Mush-r00m** [comment]
https://pastebin.com/nn42dKpT
And yeah i thought about adding the models back the way you just suggested but the structure looked different to me so i got confused.

**Comment by Mush-r00m** [comment]
Glad i could help, i have reverted back to 1.5.4 since my model list grows constantly ;)
