### ISSUE TITLE
Set Max recorded Resolution

### ISSUE THREAD

**Issue by justamonkeyname** [0xboobface/ctbrec#45]
Is there any option to set a max Resolution for recordings? 
If not it would be nice if it would be added.
So you can set for example 1080p as max and Streams with higer resolution (4k etc.) would be set to 1080 and all below 1080 will be recorded with their higest resolution.

**Comment by 0xboobface** [comment]
There is no such setting, yet. You can only enable the manual selection and choose your preferred resolution for each model. This setting should then be persistent until you remove the model from the list of recorded models.

**Comment by 0xboobface** [comment]
Added in 9da580c

**Comment by Johnex** [comment]
Hi!
Could you change this feature so that the user can enter an arbitrary resolution?
For example i have a model that has a resolution of 768, but i can only select 720, so she doesn't get recorded.

**Comment by Johnex** [comment]
Thanks!
Yeah i have noticed it for a few models already. Seems like CB can send strange resolutions, or models are setting weird options in OBS.

**Comment by 0xboobface** [comment]
Yeah, it seems, some girls don't have a clue, what they are doing. Especially on MFC only a few girls manage to stream in HD. It's 2018! And then you have girls, which stream slideshows, because they don't know anything about frame rates or they stream in 4:3, because they use their crappy laptop cam. Not to mention sound! Sometimes it makes me really sad, especially if girls are fun and have a good attitude and could do much better ranking wise. *sigh* </rant off>
