### ISSUE TITLE
Could you add fc2 live support?

### ISSUE THREAD

**Issue by mrpulpy** [0xboobface/ctbrec#54]
I noticed that you've been adding more and more sites. Is fc2 live doable?
Thanks.

**Comment by 0xboobface** [comment]
You mean this site? https://fc2livecn.com/adult/

**Comment by mrpulpy** [comment]
Yes, that's it. I think the main url is https://live.fc2.com/adult/

**Comment by 0xboobface** [comment]
So, I had a look at this site and got it to the point, where a recording should work, but the playlists I get from the server are always empty. It seems I am missing a http parameter or cookie or I don't know what.
I'm currently not working on it anymore, because I ran out of ideas and just couldn't find the problem. I'll probably get back to it some time later.

**Comment by johnthecracker** [comment]
I can get hls stream if I change browser's user agent to iphone.
Resolution is small next to not work looking at what I get.
rtmp stream is much bigger and better, and so far I have one way of recording that
with streamlink and fc2.py plugin.
Author of fc2.py plugin stopped working on that plugin for the reason of his own and removed it
but it can still be found on few places on the internet.
It may be worth looking at it if you consider supporting rtmp, if you want to.

https://www.datafilehost.com/d/3fed978b

**Comment by 0xboobface** [comment]
Did you try to open the HLS stream in a player? I can get all the information needed. I can get the master playlist and it contains the media playlists with session_token and playlist_token. But when I try to open the playlist I get a HTTP 403 error (unauthorized)

**Comment by 0xboobface** [comment]
Nevermind, I think I found out, what the problem was. The HLS playlists can be obtained over a websocket connection. What I did was to open the websocket, get the HLS urls and then close the websocket again. But the websocket has to be kept open. Otherwise you get the 403 when requesting the playlists.

**Comment by johnthecracker** [comment]
Do you have any recommendation what should I read about practical use of websockets ?
