### ISSUE TITLE
Search should return a model (if they exist)

### ISSUE THREAD

**Issue by Asynchr0nous** [0xboobface/ctbrec#57]
Others may or may not have noticed but the search function in its current state only shows models on the page your currently on, which defeats the purpose of a search function. what if the model is on the very last page? 

Also i think when searching, it would be great to show offline or private models when using the seach bar otherwise it just shows online models (as is currently)

**Comment by 0xboobface** [comment]
You have a valid point and I agree to a certain degree. First the hint in the input field said "Search". At some point I changed that to "Filter" because of this exact reason. It really only filters the currently shown models.
A real search would have to send a request to the cam site and use their search function. Definitely doable for sites with a search function, but has to be done :grin:

**Comment by Xploit3r** [comment]
I agree, this would be very useful. Especially when a girl is offline and you want to add her to the list.

Although, now with the text search feature in the format: "Sitename:Modelname". It can be directly used to add the girl to the Recording list.
