### ISSUE TITLE
Notification system for different events (like KDE notifications)

### ISSUE THREAD

**Issue by RedRhumRedRhum** [0xboobface/ctbrec#80]
Adding audio alert or desktop alerts when model goes online. (being able to select from recording list which model you may or may not want the alert)

Adding automatic browser opening for specific models from recording list when online.

**Comment by bj73** [comment]
Just as an extension/alternative to this, expand the Post Processing script setting to handle events?

ie. Instead of having just having it triggered when a recording is finished, make it a generic Event Processing script and pass the event as an argument.

So instead of just: directory; file; model; site; unixtime

You could have: directory; file; model; site; unixtime; **event**

Where **event** could be: online, offline, started, stopped, error ...
online - model is online
offline - model is offline/hidden/away/private
started - recording started
stopped - recording stopped
error - general error, eg. out of disk space, connection error, etc

Irrelevant args are null for some events, (eg. directory & file for online/offline event).

Then the script could take care of any notifications, eg. using Pushetta to push notifications to your phone.

eg. Powershell

```
# script requires Powershell 3.0 or later
# set your Pushetta API Key
$ApiKey = 'your_pushetta_api_key'
# the name of the specific channel your are posting message to
$ChannelName = 'pushetta_channel_name'
# create the uri to post your message
$Uri ='http://api.pushetta.com/api/pushes/' + $ChannelName + '/'
# specify the content type of the http request
$ContentType = "application/json"
# set the method of the http request
$Method = "POST"
# create a json message for the body of the http request
$JsonMsg = @{
                body = "Online: $($model)";
                message_type ="text/plain";
                expire ="2019-01-01"
                } | ConvertTo-JSON
# create the header of the request to store authentication info
$Header = @{}
# add your key to the header
$Header.Add("AUTHORIZATION", " Token $ApiKey");
# call http request
Invoke-RestMethod -Method $Method -Uri $Uri -Header $Header -Body $JsonMsg -ContentType $ContentType```

**Comment by bj73** [comment]
Will this be implemented for the unified server?

At the moment, it doesn't appear to use the post-processing setting - I was trying to get ffmpeg to write the TS files to a single MP4 when recording finished since it was faster to download a single file over FTP, (for me anyway), but nothing happened.
I was using the supplied pp.sh in the normal archive with an output name change.

**Comment by 0xboobface** [comment]
> but nothing happened

I knew, this would come up :smiley:. I'm gonna create a new issue for that. 

> Will this be implemented for the unified server?

I guess, it makes sense to implement this for the server, too. But of course, the set of possible actions are different. I think, running a command is the only  useful action for the server.

**Comment by bj73** [comment]
Would passing the event as an argument be easier to implement across both the server/standalone using the same events/mechanism for both?

An external script can take care of whether it's applying to server/standalone operation and process accordingly, eg. local notification, push notification, mux to single file, rename, upload (rather than use client to download), etc.

That way you don't need to incorporate a GUI interface for events, (which won't get used on the server), perhaps just add an extra arg/ENV variable to indicate what mode it's running in?

eg.
```
If ($ENV:ctbrec -eq $true) {    # true = server
  push notification (or email)
} else {                        # false = standalone
  local notification
}
```
