### ISSUE TITLE
Double click on item in Recordings tab (PART 2)

### ISSUE THREAD

**Issue by jamesjonesfor3** [0xboobface/ctbrec#85]
- Remove the "Starting Player" message
- Bug: The application takes focus a few seconds after the user's video player opens

**Comment by 0xboobface** [comment]
This was an idea / experiment. Depending on the player you are using, it can take quite some time until it shows up. I'm using mpv for example and it does not show up until it has finished buffering and started playing the video. Once the control is handed over to the player I cannot show any indication, that something is still happening in ctbrec. That's why I came up with this popup message. But if it steals the focus, that's really bad. It works fine for me with Linux / KDE.

I guess I'll remove it, or at least add a setting to disable it.

**Comment by jamesjonesfor3** [comment]
I'm using Windows 7 and mpc. The application steals focus when the "Starting Player" message disappears. Removing the message should fix it.

**Comment by nim56** [comment]
I noticed that if the path to the recordings directory has spaces, the double click on item feature bugs.

**Comment by 0xboobface** [comment]
> I noticed that if the path to the recordings directory has spaces, the double click on item feature bugs.

Fixed in 88bddcb

> Remove the "Starting Player" message

I added a setting to toggle it (c17dcc4). Default is off, since most users use Windows and it steals the focus on Windows
