### ISSUE TITLE
Add Streamate

### ISSUE THREAD

**Issue by 0xboobface** [0xboobface/ctbrec#89]

**Comment by Asynchr0nous** [comment]
I already have a full working script for this site and its alias but one issue all these sites have is that alot of the times it says that a model was online on a certain date/time when in fact they weren't (i upgraded my scripts multiples times thinking maybe something is wrong with them but the fact is even if a model logs in (not stream) it will show as online on their site). the problem is that even though the script won't record in these cases, its annoying as fuck because you can't verify if a model was actually online or not.

**Comment by 0xboobface** [comment]
Metcams is only a whitelabel of Streamate. xhamstercams.com is antoher one and there are probably much more. Support for Streamate has been added with e1c16cd. Everything except tipping is working.
